Modal Forms
Moved forms from separate modals into one request modal. Forms should hide when buttons are pressed.

Removed pages holding the forms prior and moved to one central page.
Moved modal content from user request page to a new page to hold modal

Current existing error when trying to open modal :
NullInjectorError: R3InjectorError(Module)[FormBuilder -> FormBuilder -> FormBuilder -> FormBuilder]:    NullInjectorError: No provider for FormBuilder

Working on fix for modal forms